networks:
  net:
    driver: bridge
    name: game
    ipam:
      config:
      - subnet: 10.0.0.0/8
        gateway: 10.0.0.1
    driver_opts:
      com.docker.network.bridge.name: "game"

services:
  vulnbox:
    build: ./vulnbox
    image: vulnbox
    container_name: vulnbox
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net:
        ipv4_address: 10.0.1.0

  forcad:
    build: ./ForcAD
    image: forcad
    container_name: forcad
    networks:
      net:
        ipv4_address: 10.10.10.10

  vpn:
    image: alekslitvinenk/openvpn
    container_name: vpn
    networks:
      net:
        ipv4_address: 10.0.0.2
    devices:
      - /dev/net/tun
    ports:
      - "1195:1195/udp"
      - "8888:8080/tcp"
    environment:
      - HOST_ADDR=185.186.26.128
      - HOST_TUN_PORT=1195
    volumes:
      - ./vpn/openvpn-config.conf:/etc/openvpn/server.conf

