# Generated by Django 5.1.7 on 2025-03-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default='2024-01-01T00:00:00', verbose_name='Время начала')),
                ('duration', models.PositiveIntegerField(default=540, help_text='Например: 540 = 9 часов', verbose_name='Длительность (в минутах)')),
                ('services', models.JSONField(default=list, verbose_name='Список сервисов')),
                ('players', models.JSONField(default=list, verbose_name='Список игроков')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'db_table': 'games',
                'ordering': ['-start'],
            },
        ),
    ]
