game:
  mode: classic
  round_time: 60
  start_time: 2023-12-08 10:00:00
  timezone: Europe/Moscow
  default_score: 2500
  flag_lifetime: 10
  game_hardness: 15.0
  inflation: true

tasks:
- checker: oilmarket/checker.py
  checker_timeout: 15
  checker_type: gevent_pfr
  gets: 1
  name: oilmarket
  places: 1
  puts: 1
- checker: neftetochka/checker.py
  checker_timeout: 10
  checker_type: gevent
  gets: 1
  name: neftetochka
  places: 1
  puts: 1
- checker: explorers/checker.py
  checker_timeout: 15
  checker_type: gevent_pfr
  gets: 1
  name: explorers
  places: 1
  puts: 1
- checker: bluwal/checker.py
  checker_timeout: 10
  checker_type: gevent_pfr
  gets: 1
  name: bluwal
  places: 1
  puts: 1


teams:
- ip: 10.80.1.2
  name: NPC
- ip: 10.80.2.2
  name: players
